[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "browsing-topics=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
